### ISSUE TITLE
Filter/return data by PoS tag

### ISSUE THREAD

**Issue by stefano-bragaglia** [Manwholikespie/thesaurus-api#1]
It's not really an issue but a couple of suggestions/requests... 
(I'm not sure if this is the right place to do so: if not, my apologies in advance!)

Wouldn't it be great if the output would be organised by PoS tag (i.e.: NOUN, ADJ, VERB, etc.)?
I.e.:`{'ADJ': {'ant1': ['boiling', ...], 'ant2': ['pleasant', ...], ...}, 'ADV': {...}}`

Wouldn't it be even better if we could address requests by PoS tag? 
I.e.: `findSynonyms('big', rank=[3], tags=[ADJ, ADV])`

By the way, do you know if too many requests per second result in user IP being banned?
Thanks in advance and keep up the great work.

**Comment by Manwholikespie** [comment]
Mmm I like that idea. Currently, you can use findWordTotal() to get all the definitions of a word, which are grouped as
```python
>>> findWordTotal('box')
{
    '0' : {
        'partOfSpeech' : 'noun',
        'meaning' : 'container, often square or rectangular',
        'syn3' : [ ... ],
        'syn2' : [ ... ],
        # and so on
    },
    '1' : {
        'partOfSpeech' : 'verb',
        'meaning' : 'place in square or rectangular container',
        'syn3' : [ ... ]
    },
    '2' : {
        'partOfSpeech' : 'verb',
        'meaning' : 'punch competitively',
        'syn3' : [ ... ]
    }
}
```
Looking back at this, I'm not quite sure I was in a totally sane state of mind when I wrote this, as I can't remember why I didn't just make it a list of dicts rather than a dict of dicts. I'll have to change that.

So, with this you could do something like:
```python
filter(lambda x: x['partOfSpeech'] == 'adj', findWordTotal('box'))
```
for finding the definition types you want. But again, it would have to be in list form. I'm not sure if using the list() function would automatically convert it and throw away the keys, but if not I'll try to work on fixing that when I have some free time.

All of this of course is assuming you are talking about grouping the primary word's multiple definitions by their partOfSpeech. If you wanted to get each synonym's POS, you'd have to fetch the page for each one, as thesaurus.com doesn't give you this info on the first page of the word you search for.

Also, I do like the idea of being able to have a tags=[] option in functions. I should add some of those optional function arguments. That would indeed be nice. The only problem I could see coming up is that, like the example I gave above for findWordTotal('box'), here we have two vastly different definitions with the same POS. I don't think it would be a good idea to group all of the synonyms together across the definitions. Maybe I am misunderstanding how you would want them organized?

As for the IP bans, I don't think they do this. I used this for a program a few months back (sadly, I still haven't come around to finishing it) that would take a normal sentence and turn it into a Haiku. It involved finding copious amounts of synonyms for every word in the sentence. I didn't get banned. I would still be decently careful about doing thousands of requests, though.

Thanks for your interest in this.

**Comment by stefano-bragaglia** [comment]
Thanks for the answer! 

I think this solves the issue for now, still I look forward to see all the improvements that you plan to add.

I'm trying to find `<subject, verb, object>` triples in sentences (mostly using spaCy), i.e.: `"Bob has been working for ACME for 5 years"` leading to `<Bob, works_for, ACME>` and "group them together" so that I can understand that `<Bob, works_for, ACME>` and `<Bob, is_employed_by, ACME>` are the same. One way of doing so, would be by considering synonyms for verbs. I had a look at `wordNet` (maybe `verbNet`) but it usually contain crazy synonyms and it's rather complicated to order them properly. One way to reduce the noise would be to filter by PoS tag (by verb in this specific case) so that I get only synonyms that can be used as such. On `thesaurus.com` there is a drop down menu called `show` next to the name of the term to search where you can select the specific PoS you need (or all). Of Safari, if I change that value nothing happens, but maybe we can force it by adding a parameter on the URL to call. The motivation is if we get rid of irrelevant synonyms since the beginning, we conversely get more relevant content on the the first page to collect.

On a completely different angle, some time ago I stumbled upon [this page](https://words.bighugelabs.com/api.php): so far as I remember the API is free to use but it doesn't provide any kind of ordering over the resulting synonyms.

Many thanks for now!

**Comment by Manwholikespie** [comment]
Alright, sorry it took so long. I was doing a summer course last month, and then got busy with some other stuff which distracted me from this. Filtering is complete.

Sadly, I changed *a lot* of the source code. So, you can either import from old.py (which will eventually be deprecated— all of the old functions were confusingly named and did a lot of the same things, just with different return types), or you can change your code to incorporate the new stuff.

The README should have everything you need to understand how to use the filtering. I went ahead and added new word data such as length, complexity, and form. Also, I tried to make the scraping as linear a process as possible, so the code now runs 30% faster even with all the new toys.

Enjoy! 😄
